language: ruby

os:
  - linux

rvm:
  - 2.5
  - 2.6
  - 2.7

install:
  - bundle install

before_script:
  - ruby --version
  - bundle --version

script: 
  - rubocop
  - './influx_hs110_energy.rb -h'
